---
- name: Install apt dependencies
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
    cache_valid_time: 86400
  loop:
    - name: unzip
      state: latest

- name: "Ensure group '{{ bitping_group }}' exists"
  group:
    name: "{{ bitping_group }}"
    state: present

- name: "Ensure user '{{ bitping_user }}' exists"
  user:
    name: "{{ bitping_user }}"
    group: "{{ bitping_group }}"
    create_home: true
    state: present
    shell: /bin/bash

- name: "Make sure directories exist"
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ bitping_user_home }}"
    - "{{ bitping_directory }}"

- name: "Download Bitping from '{{ bitping_download_url }}' and unarchive it at '{{ bitping_directory }}'"
  unarchive:
    src: "{{ bitping_download_url }}"
    dest: "{{ bitping_directory }}"
    remote_src: true

- name: "Figuring out whether all the credentials are properly set. If one of them is not, it is essential that the token be fetched from the login API"
  set_fact:
    bitping_rest_login_required: "{{ not bitping_credentials_email or not bitping_credentials_password or not bitping_credentials_id or not bitping_credentials_name or not bitping_credentials_token }}"

- name: "Get JWT token from '{{ bitping_login_url }}'"
  uri:
    url: "{{ bitping_login_url }}"
    method: POST
    return_content: yes
    body_format: json
    body: {"email": "{{ bitping_credentials_email }}", "password": "{{ bitping_credentials_password }}"}
    status_code: 200
  no_log: true
  run_once: true
  register: login_response
  when: bitping_rest_login_required is true

- name: "Set facts based on the login response"
  set_fact:
    bitping_credentials_id: "{{login_response.json.id}}"
    bitping_credentials_name: "{{login_response.json.name}}"
    bitping_credentials_email: "{{login_response.json.email}}"
    bitping_credentials_token: "{{login_response.json.token}}"
  no_log: true
  when: bitping_rest_login_required is true

- name: "Create the credentials file at '{{ bitping_credentials_file_path }}'"
  template:
    src: credentials.json.j2
    dest: "{{ bitping_credentials_file_path }}"
    owner: "{{ bitping_user }}"
    group: "{{ bitping_group }}"
    mode: '0644'
  no_log: true

#TODO: Create the systemd file to restart bitping

#TODO: Make sure bitping service is enabled and up and running
