---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  tasks:
    - name: "Include ansible-role-bitping"
      include_role:
        name: "ansible-role-bitping"
